// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAgenda.Infra.Arquivos.Compartilhado;

#nullable disable

namespace eAgenda.Infra.Arquivos.Migrations
{
    [DbContext(typeof(eAgendaDbContext))]
    partial class eAgendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eAgenda.WinApp.ModuloCompromisso.Compromisso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("DataCompromisso")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Localização")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Termino")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.ToTable("TBCompromisso", (string)null);
                });

            modelBuilder.Entity("eAgenda.WinApp.ModuloContato.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBContato", (string)null);
                });

            modelBuilder.Entity("eAgenda.WinApp.ModuloTarefa.ItemTarefa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("ItemTarefa");
                });

            modelBuilder.Entity("eAgenda.WinApp.ModuloTarefa.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataConclusao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DataCriacao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TBTarefa", (string)null);
                });

            modelBuilder.Entity("eAgenda.WinApp.ModuloTarefa.ItemTarefa", b =>
                {
                    b.HasOne("eAgenda.WinApp.ModuloTarefa.Tarefa", "Tarefa")
                        .WithMany("Itens")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("eAgenda.WinApp.ModuloTarefa.Tarefa", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
